//**********************************************************************************//
//                                                                                  //
//                                       IMAGE                                      //
//                                                                                  //
//**********************************************************************************//

IMAGE image_QUESTION_0              "map/trivia/questions/tiles_QUESTION_0.png"                 NONE ALL
IMAGE image_QUESTION_1              "map/trivia/questions/tiles_QUESTION_1.png"                 NONE ALL
IMAGE image_QUESTION_2              "map/trivia/questions/tiles_QUESTION_2.png"                 NONE ALL
IMAGE image_QUESTION_3              "map/trivia/questions/tiles_QUESTION_3.png"                 NONE ALL
IMAGE image_QUESTION_4              "map/trivia/questions/tiles_QUESTION_4.png"                 NONE ALL
IMAGE image_QUESTION_5              "map/trivia/questions/tiles_QUESTION_5.png"                 NONE ALL
IMAGE image_QUESTION_6              "map/trivia/questions/tiles_QUESTION_6.png"                 NONE ALL
IMAGE image_QUESTION_7              "map/trivia/questions/tiles_QUESTION_7.png"                 NONE ALL
IMAGE image_QUESTION_8              "map/trivia/questions/tiles_QUESTION_8.png"                 NONE ALL
IMAGE image_QUESTION_9              "map/trivia/questions/tiles_QUESTION_9.png"                 NONE ALL
IMAGE image_QUESTION_10             "map/trivia/questions/tiles_QUESTION_10.png"                NONE ALL
IMAGE image_QUESTION_11             "map/trivia/questions/tiles_QUESTION_11.png"                NONE ALL
IMAGE image_QUESTION_12             "map/trivia/questions/tiles_QUESTION_12.png"                NONE ALL
IMAGE image_QUESTION_13             "map/trivia/questions/tiles_QUESTION_13.png"                NONE ALL
IMAGE image_QUESTION_14             "map/trivia/questions/tiles_QUESTION_14.png"                NONE ALL
IMAGE image_QUESTION_15             "map/trivia/questions/tiles_QUESTION_15.png"                NONE ALL
IMAGE image_QUESTION_16             "map/trivia/questions/tiles_QUESTION_16.png"                NONE ALL
IMAGE image_QUESTION_17             "map/trivia/questions/tiles_QUESTION_17.png"                NONE ALL
IMAGE image_QUESTION_18             "map/trivia/questions/tiles_QUESTION_18.png"                NONE ALL
IMAGE image_QUESTION_19             "map/trivia/questions/tiles_QUESTION_19.png"                NONE ALL
IMAGE image_QUESTION_20             "map/trivia/questions/tiles_QUESTION_20.png"                NONE ALL
IMAGE image_QUESTION_21             "map/trivia/questions/tiles_QUESTION_21.png"                NONE ALL
IMAGE image_QUESTION_22             "map/trivia/questions/tiles_QUESTION_22.png"                NONE ALL
IMAGE image_QUESTION_23             "map/trivia/questions/tiles_QUESTION_23.png"                NONE ALL
IMAGE image_QUESTION_24             "map/trivia/questions/tiles_QUESTION_24.png"                NONE ALL
IMAGE image_QUESTION_25             "map/trivia/questions/tiles_QUESTION_25.png"                NONE ALL
IMAGE image_QUESTION_26             "map/trivia/questions/tiles_QUESTION_26.png"                NONE ALL
IMAGE image_QUESTION_27             "map/trivia/questions/tiles_QUESTION_27.png"                NONE ALL
IMAGE image_QUESTION_28             "map/trivia/questions/tiles_QUESTION_28.png"                NONE ALL
IMAGE image_QUESTION_29             "map/trivia/questions/tiles_QUESTION_29.png"                NONE ALL
IMAGE image_QUESTION_30             "map/trivia/questions/tiles_QUESTION_30.png"                NONE ALL
IMAGE image_QUESTION_31             "map/trivia/questions/tiles_QUESTION_31.png"                NONE ALL
IMAGE image_QUESTION_32             "map/trivia/questions/tiles_QUESTION_32.png"                NONE ALL
IMAGE image_QUESTION_33             "map/trivia/questions/tiles_QUESTION_33.png"                NONE ALL
IMAGE image_QUESTION_34             "map/trivia/questions/tiles_QUESTION_34.png"                NONE ALL
IMAGE image_QUESTION_35             "map/trivia/questions/tiles_QUESTION_35.png"                NONE ALL
IMAGE image_QUESTION_36             "map/trivia/questions/tiles_QUESTION_36.png"                NONE ALL
IMAGE image_QUESTION_37             "map/trivia/questions/tiles_QUESTION_37.png"                NONE ALL
IMAGE image_QUESTION_38             "map/trivia/questions/tiles_QUESTION_38.png"                NONE ALL
IMAGE image_QUESTION_39             "map/trivia/questions/tiles_QUESTION_39.png"                NONE ALL
IMAGE image_QUESTION_40             "map/trivia/questions/tiles_QUESTION_40.png"                NONE ALL
IMAGE image_QUESTION_41             "map/trivia/questions/tiles_QUESTION_41.png"                NONE ALL
IMAGE image_QUESTION_42             "map/trivia/questions/tiles_QUESTION_42.png"                NONE ALL
IMAGE image_QUESTION_43             "map/trivia/questions/tiles_QUESTION_43.png"                NONE ALL
IMAGE image_QUESTION_44             "map/trivia/questions/tiles_QUESTION_44.png"                NONE ALL
IMAGE image_QUESTION_45             "map/trivia/questions/tiles_QUESTION_45.png"                NONE ALL
IMAGE image_QUESTION_46             "map/trivia/questions/tiles_QUESTION_46.png"                NONE ALL
IMAGE image_QUESTION_47             "map/trivia/questions/tiles_QUESTION_47.png"                NONE ALL
IMAGE image_QUESTION_48             "map/trivia/questions/tiles_QUESTION_48.png"                NONE ALL
IMAGE image_QUESTION_49             "map/trivia/questions/tiles_QUESTION_49.png"                NONE ALL
IMAGE image_QUESTION_50             "map/trivia/questions/tiles_QUESTION_50.png"                NONE ALL
IMAGE image_QUESTION_51             "map/trivia/questions/tiles_QUESTION_51.png"                NONE ALL
IMAGE image_QUESTION_52             "map/trivia/questions/tiles_QUESTION_52.png"                NONE ALL
IMAGE image_QUESTION_53             "map/trivia/questions/tiles_QUESTION_53.png"                NONE ALL
IMAGE image_QUESTION_54             "map/trivia/questions/tiles_QUESTION_54.png"                NONE ALL
IMAGE image_QUESTION_55             "map/trivia/questions/tiles_QUESTION_55.png"                NONE ALL
IMAGE image_QUESTION_56             "map/trivia/questions/tiles_QUESTION_56.png"                NONE ALL
//IMAGE image_QUESTION_57             "map/trivia/questions/tiles_QUESTION_57.png"                NONE ALL
//IMAGE image_QUESTION_58             "map/trivia/questions/tiles_QUESTION_58.png"                NONE ALL
//IMAGE image_QUESTION_59             "map/trivia/questions/tiles_QUESTION_59.png"                NONE ALL
//IMAGE image_QUESTION_60             "map/trivia/questions/tiles_QUESTION_60.png"                NONE ALL
//IMAGE image_QUESTION_61             "map/trivia/questions/tiles_QUESTION_61.png"                NONE ALL
//IMAGE image_QUESTION_62             "map/trivia/questions/tiles_QUESTION_62.png"                NONE ALL
//IMAGE image_QUESTION_63             "map/trivia/questions/tiles_QUESTION_63.png"                NONE ALL
//IMAGE image_QUESTION_64             "map/trivia/questions/tiles_QUESTION_64.png"                NONE ALL
