#ifndef _RES_SPRITES_WAITERS_H_
#define _RES_SPRITES_WAITERS_H_

extern const SpriteDefinition tiles_SPR_LARRY1_WAITERS;
extern const SpriteDefinition tiles_SPR_LARRY2_WAITERS;
extern const SpriteDefinition tiles_SPR_CURLY1_WAITERS;
extern const SpriteDefinition tiles_SPR_CURLY2_WAITERS;
extern const SpriteDefinition tiles_SPR_WOMAN1_WAITERS;
extern const SpriteDefinition tiles_SPR_WOMAN2_WAITERS;
extern const SpriteDefinition tiles_SPR_MAN1_WAITERS;
extern const SpriteDefinition tiles_SPR_MAN2_WAITERS;

#endif // _RES_SPRITES_WAITERS_H_
