#ifndef _RES_SPRITES_WAITERS_H_
#define _RES_SPRITES_WAITERS_H_

extern const SpriteDefinition tiles_SPR_HAND_WAITERS;
extern const SpriteDefinition tiles_SPR_LARRY1_WAITERS;
extern const SpriteDefinition tiles_SPR_LARRY2_WAITERS;
extern const SpriteDefinition tiles_SPR_CURLY1_WAITERS;
extern const SpriteDefinition tiles_SPR_CURLY2_WAITERS;
extern const SpriteDefinition tiles_SPR_MOE1_WAITERS;
extern const SpriteDefinition tiles_SPR_MOE2_WAITERS;
extern const SpriteDefinition tiles_SPR_WOMAN1_WAITERS;
extern const SpriteDefinition tiles_SPR_WOMAN2_WAITERS;
extern const SpriteDefinition tiles_SPR_MAN1_1_WAITERS;
extern const SpriteDefinition tiles_SPR_MAN1_2_WAITERS;
extern const SpriteDefinition tiles_SPR_MAN2_1_WAITERS;
extern const SpriteDefinition tiles_SPR_MAN2_2_WAITERS;

#endif // _RES_SPRITES_WAITERS_H_
